### PR TITLE
Update the randomness to be handled on the mustachify side.

### PR DESCRIPTION
**Pull request by louim**
According to the Mustachio code at: https://github.com/afeld/mustachio/blob/master/lib/mustachio/app.rb#L60, if we use `rand` instead of a number, randomness is already handled on the mustachio's side, so I don't think we need to do it on our side too.

### CODE REVIEW

**Comment by parkr** [comment]
Nice!

**Comment by afeld** [comment]
Note that this means it _could_ show a different mustache to each person that gets sent the link.

**Comment by technicalpickles** [comment]
Ah, that's a good point. Probably should revert in that case.

**Comment by louim** [comment]
I see your point, my main motivation for doing this change is the ability to add more mustaches on mustachify side, without having to modify the external script each time.

**Comment by afeld** [comment]
Maybe a good solution would be to have `/rand` redirect to one of the numbers on the mustachio side?

**Comment by louim** [comment]
@afeld I think that would be the best option :+1:

**Comment by afeld** [comment]
Though I guess this script would then need to make an initial request to get the new URL, then respond back with that new `Location`.

**Pull request merged**
